-- Savings pots: money deliberately moved out of the bank account into a
-- separate savings/deposit account.
--
-- A pot holds a balance snapshot the same way `account` and `credit_card` do.
-- Movements are ordinary `ledger_entry` rows on the pot's `savings:<id>`
-- channel (usually generated by a recurring_template), so a contribution
-- reduces the projected bank balance like any other outflow while the shared
-- forecast engine projects the pot balance forward alongside it.
--
-- Channels are opaque strings elsewhere in the schema (`cc:<cardId>` has no FK
-- either), so no foreign key is declared here; the API validates that a
-- `savings:` channel resolves to an existing pot on write.

CREATE TABLE IF NOT EXISTS savings_pot (
  id      TEXT PRIMARY KEY,
  name    TEXT NOT NULL,
  balance REAL NOT NULL DEFAULT 0 CHECK (balance >= 0),
  as_of   TEXT NOT NULL
);
