import type {
  CreditCard,
  DailyProjection,
  ForecastResult,
  LedgerEntry,
  PaymentProgress,
  ProjectionCharge,
  RecurringTemplate,
} from '@expenses/shared';
import {
  addDays,
  addMonths,
  firstBillingDayStrictlyAfter,
  generateVirtualOccurrences,
  paymentProgress,
} from '@expenses/shared';

export interface BilledChargeRow {
  date: string;
  description: string;
  amount: number;
  /** True when this sub-row is shown as already accounted for, not forecast action. */
  past?: boolean;
  /** True for entries that were marked cleared (status === 'cleared'). */
  cleared?: boolean;
  /** Optional X/Y badge — set when this row was generated by a fixed-term recurring template. */
  progress?: PaymentProgress | null;
  /** Set when this row was generated from a recurring template, so the
   * UI can offer a Skip button on future occurrences. */
  recurringId?: string;
}

export interface ChargeItem {
  kind: 'charge';
  date: string;
  description: string;
  amount: number;
  channel: 'bank' | 'cc';
  cardId?: string;
  /** Set for bank-channel charges (single ledger entry). Absent for cc-bill rollups. */
  entryId?: string;
  /** True for rows shown as already accounted for, not forecast actions. */
  past?: boolean;
  /** True for entries that were marked cleared (status === 'cleared'). */
  cleared?: boolean;
  /** Individual charges aggregated into this cc-bill (chronological). */
  billedEntries?: BilledChargeRow[];
  /** Stable key for the expand/collapse toggle of a cc-bill. */
  billKey?: string;
  /** Optional X/Y badge — set when this charge came from a fixed-term recurring template. */
  progress?: PaymentProgress | null;
  /** Set when this charge was generated from a recurring template, so
   * the UI can offer a Skip button on future occurrences. */
  recurringId?: string;
}

export interface AnchorItem {
  kind: 'anchor';
  date: string;
  balance: number;
  belowThreshold: boolean;
}

export type TimelineItem = ChargeItem | AnchorItem;
export type ChannelFilter = 'all' | 'bank' | 'cc' | 'anchors';

export interface ForecastTimelineInput {
  forecast: ForecastResult;
  threshold: number;
  filter: ChannelFilter;
  ledger: ReadonlyArray<LedgerEntry>;
  templates: ReadonlyArray<RecurringTemplate>;
  cards: ReadonlyArray<CreditCard>;
  todayIso?: string;
}

/** Charges + anchors interleaved chronologically for the forecast timeline. */
export const buildForecastTimeline = ({
  forecast,
  threshold,
  filter,
  ledger,
  templates,
  cards,
  todayIso = todayIsoLocal(),
}: ForecastTimelineInput): TimelineItem[] => {
  const items: TimelineItem[] = [];

  const windowStart = lastPastAnchor(todayIso);
  const visibleStart = forecast.days[0]?.date ?? todayIso;
  const billLookbackStart = addMonths(windowStart, -1);

  const overriddenOccurrences = new Set<string>();
  for (const e of ledger) {
    if (e.occurrenceKey) overriddenOccurrences.add(e.occurrenceKey);
  }

  const virtualBillCandidates =
    billLookbackStart < visibleStart
      ? generateVirtualOccurrences(templates, billLookbackStart, visibleStart).filter(
          (e) =>
            e.date < visibleStart &&
            (!e.occurrenceKey || !overriddenOccurrences.has(e.occurrenceKey)),
        )
      : [];
  const virtualPast = virtualBillCandidates.filter((e) => e.date >= windowStart);
  const persistedBillCandidates = ledger.filter(
    (e) =>
      e.date >= billLookbackStart &&
      e.date <= forecast.endDate &&
      (e.date < visibleStart || e.status === 'cleared'),
  );
  const persistedHistorical = persistedBillCandidates.filter((e) => e.date >= windowStart);

  const templatesById = new Map(templates.map((template) => [template.id, template]));
  const cardsById = new Map(cards.map((card) => [card.id, card]));

  const progressForEntry = (entry: { date: string; recurringId?: string }): PaymentProgress | null => {
    if (!entry.recurringId) return null;
    const template = templatesById.get(entry.recurringId);
    if (!template) return null;
    return paymentProgress(template, entry.date);
  };

  const toChargeItem = (
    date: string,
    charge: ProjectionCharge,
    accountedBilledEntries: ReadonlyArray<LedgerEntry> = [],
  ): ChargeItem => {
    if (charge.source.kind === 'cc-bill') {
      const seen = new Set<string>();
      const toBilledRow = (entry: LedgerEntry, accounted: boolean): BilledChargeRow => ({
        date: entry.date,
        description: entry.description,
        amount: entry.amount,
        progress: progressForEntry(entry),
        ...(accounted ? { past: true } : {}),
        ...(entry.status === 'cleared' ? { cleared: true } : {}),
        ...(entry.recurringId ? { recurringId: entry.recurringId } : {}),
      });
      const billed: BilledChargeRow[] = [];
      for (const entry of accountedBilledEntries) {
        seen.add(entry.id);
        billed.push(toBilledRow(entry, true));
      }
      for (const entry of charge.source.billedEntries ?? []) {
        if (seen.has(entry.id)) continue;
        seen.add(entry.id);
        billed.push(toBilledRow(entry, false));
      }
      billed.sort((a, b) => (a.date < b.date ? -1 : a.date > b.date ? 1 : 0));
      const entriesTotal = billed.reduce((sum, entry) => sum + entry.amount, 0);
      const opening = charge.amount - entriesTotal;
      const sub: BilledChargeRow[] = [];
      if (Math.abs(opening) > 0.005) {
        sub.push({
          date,
          description: 'Opening balance (from Excel snapshot)',
          amount: opening,
          past: true,
        });
      }
      for (const row of billed) sub.push(row);
      if (sub.length === 0) {
        sub.push({
          date,
          description: 'No itemized charges in this cycle.',
          amount: charge.amount,
        });
      }
      return {
        kind: 'charge',
        date,
        description: charge.description,
        amount: charge.amount,
        channel: 'cc',
        cardId: charge.source.cardId,
        billedEntries: sub,
        billKey: `${date}:${charge.source.cardId}`,
      };
    }

    const { entryId, recurringId } = charge.source;
    const recurringIdResolved =
      recurringId ?? ledger.find((entry) => entry.id === entryId)?.recurringId;
    return {
      kind: 'charge',
      date,
      description: charge.description,
      amount: charge.amount,
      channel: 'bank',
      entryId,
      progress: recurringIdResolved
        ? progressForEntry({ date, recurringId: recurringIdResolved })
        : null,
      ...(recurringIdResolved ? { recurringId: recurringIdResolved } : {}),
    };
  };

  const toPastChargeItem = (entry: LedgerEntry): ChargeItem => {
    const isCc = entry.channel.startsWith('cc:');
    const cardId = isCc ? entry.channel.slice(3) : undefined;
    const item: ChargeItem = {
      kind: 'charge',
      date: entry.date,
      description: entry.description,
      amount: entry.amount,
      channel: isCc ? 'cc' : 'bank',
      entryId: entry.id,
      past: true,
      cleared: entry.status === 'cleared',
      progress: entry.recurringId ? progressForEntry(entry) : null,
    };
    if (cardId) item.cardId = cardId;
    if (entry.recurringId) item.recurringId = entry.recurringId;
    return item;
  };

  const rollsIntoCreditCardBill = (entry: LedgerEntry): boolean => {
    if (!entry.channel.startsWith('cc:')) return false;
    const card = cardsById.get(entry.channel.slice(3));
    return card != null && card.mode !== 'debit';
  };

  const accountedCreditCardEntriesForBill = (
    cardId: string,
    billDate: string,
    entries: ReadonlyArray<LedgerEntry>,
    start: string,
  ): LedgerEntry[] => {
    const card = cardsById.get(cardId);
    if (!card || card.mode === 'debit') return [];
    const openingBillDate = firstBillingDayStrictlyAfter(card.asOf, card.billingDayOfMonth);
    return entries.filter((entry) => {
      if (entry.date < start || entry.channel !== `cc:${cardId}`) return false;
      const entryBillDate = firstBillingDayStrictlyAfter(entry.date, card.billingDayOfMonth);
      if (entryBillDate !== billDate) return false;
      if (entry.date <= card.asOf) {
        return card.currentDebit !== 0 && billDate === openingBillDate;
      }
      return true;
    });
  };

  const inPastWindow = (date: string): boolean =>
    date >= windowStart && date < visibleStart && date <= forecast.endDate;

  const pastCreditCardBillItems = (
    virtuals: ReadonlyArray<LedgerEntry>,
    persisted: ReadonlyArray<LedgerEntry>,
  ): ChargeItem[] => {
    type BillBucket = {
      billDate: string;
      cardId: string;
      entries: LedgerEntry[];
      accountedEntries: LedgerEntry[];
      openingDebit: number;
    };

    const buckets = new Map<string, BillBucket>();
    const bucketFor = (cardId: string, billDate: string): BillBucket => {
      const key = `${billDate}:${cardId}`;
      let bucket = buckets.get(key);
      if (!bucket) {
        bucket = { billDate, cardId, entries: [], accountedEntries: [], openingDebit: 0 };
        buckets.set(key, bucket);
      }
      return bucket;
    };

    for (const card of cards) {
      if (card.mode === 'debit' || card.currentDebit === 0) continue;
      const billDate = firstBillingDayStrictlyAfter(card.asOf, card.billingDayOfMonth);
      if (inPastWindow(billDate)) {
        bucketFor(card.id, billDate).openingDebit += card.currentDebit;
      }
    }

    for (const entry of [...virtuals, ...persisted]) {
      if (!entry.channel.startsWith('cc:')) continue;
      const cardId = entry.channel.slice(3);
      const card = cardsById.get(cardId);
      if (!card || card.mode === 'debit') continue;
      const billDate = firstBillingDayStrictlyAfter(entry.date, card.billingDayOfMonth);
      if (inPastWindow(billDate)) {
        const bucket = bucketFor(cardId, billDate);
        const openingBillDate = firstBillingDayStrictlyAfter(card.asOf, card.billingDayOfMonth);
        if (entry.date <= card.asOf && card.currentDebit !== 0 && billDate === openingBillDate) {
          bucket.accountedEntries.push(entry);
        } else {
          bucket.entries.push(entry);
        }
      }
    }

    const rows: ChargeItem[] = [];
    for (const bucket of buckets.values()) {
      const card = cardsById.get(bucket.cardId);
      if (!card) continue;
      const entriesTotal = bucket.entries.reduce((sum, entry) => sum + entry.amount, 0);
      const amount = entriesTotal - bucket.openingDebit;
      const parts: string[] = [];
      if (bucket.openingDebit > 0) parts.push('opening balance');
      if (bucket.entries.length > 0) {
        parts.push(`${bucket.entries.length} charge${bucket.entries.length === 1 ? '' : 's'}`);
      }
      const summary = parts.length > 0 ? parts.join(' + ') : '0 charges';
      const row = toChargeItem(
        bucket.billDate,
        {
          description: `Credit card bill (${card.name}, ${summary})`,
          amount,
          source: { kind: 'cc-bill', cardId: bucket.cardId, billedEntries: bucket.entries.slice() },
        },
        bucket.accountedEntries,
      );
      row.past = true;
      rows.push(row);
    }
    return rows;
  };

  if (filter !== 'anchors') {
    const historicalBillRows = pastCreditCardBillItems(
      virtualBillCandidates,
      persistedBillCandidates,
    );

    for (const entry of [...virtualPast, ...persistedHistorical]) {
      if (rollsIntoCreditCardBill(entry)) continue;
      const row = toPastChargeItem(entry);
      if (filter === 'all' || row.channel === filter) {
        items.push(row);
      }
    }
    for (const row of historicalBillRows) {
      if (filter === 'all' || row.channel === filter) {
        items.push(row);
      }
    }
  }

  for (const day of forecast.days) {
    if (filter !== 'anchors') {
      for (const charge of day.charges) {
        const row = toChargeItem(
          day.date,
          charge,
          charge.source.kind === 'cc-bill'
            ? accountedCreditCardEntriesForBill(
                charge.source.cardId,
                day.date,
                [...virtualBillCandidates, ...persistedBillCandidates],
                billLookbackStart,
              )
            : [],
        );
        if (filter === 'all' || row.channel === filter) {
          items.push(row);
        }
      }
    }
    if (day.isAnchor) {
      items.push({
        kind: 'anchor',
        date: day.date,
        balance: day.balance,
        belowThreshold: day.balance < threshold,
      });
    }
  }

  return items.sort((a, b) => {
    if (a.date !== b.date) return a.date < b.date ? -1 : 1;
    if (a.kind === b.kind) return 0;
    return a.kind === 'anchor' ? 1 : -1;
  });
};

export interface CurrentPeriodInput {
  forecast: ForecastResult;
  ledger: ReadonlyArray<LedgerEntry>;
  templates: ReadonlyArray<RecurringTemplate>;
  cards: ReadonlyArray<CreditCard>;
  todayIso?: string;
}

/** A timeline charge item turned into a `ProjectionCharge` for the chart. */
const chargeFromItem = (item: ChargeItem): ProjectionCharge => {
  if (item.channel === 'cc') {
    return {
      description: item.description,
      amount: item.amount,
      source: { kind: 'cc-bill', cardId: item.cardId ?? '', billedEntries: [] },
    };
  }
  return {
    description: item.description,
    amount: item.amount,
    source: {
      kind: 'ledger',
      entryId: item.entryId ?? '',
      ...(item.recurringId ? { recurringId: item.recurringId } : {}),
    },
  };
};

/**
 * Daily bank-balance projections for the *current* anchor period — the
 * already-elapsed days (back to the previous anchor / 10th) followed by the
 * projected days through and including the next anchor day.
 *
 * The forecast pipeline only emits days from the snapshot date (`asOf`)
 * onward and drops charges already reflected in the bank balance, so when the
 * user's last balance snapshot is today there is no elapsed history in
 * `forecast.days`/`priorDays`. To draw the elapsed part we reuse the same
 * past records the timeline shows (`buildForecastTimeline`) and reconstruct
 * the bank balance *backward* from today's opening balance: each elapsed day's
 * balance is today's balance minus the net of the charges that happened after
 * it. This keeps the elapsed line continuous with the projected line.
 */
export const buildCurrentPeriodDays = ({
  forecast,
  ledger,
  templates,
  cards,
  todayIso = todayIsoLocal(),
}: CurrentPeriodInput): DailyProjection[] => {
  const visibleStart = forecast.days[0]?.date ?? todayIso;

  // Projected part: days from today through (and including) the next anchor.
  const anchorIdx = forecast.days.findIndex((d) => d.isAnchor);
  const forward = anchorIdx >= 0 ? forecast.days.slice(0, anchorIdx + 1) : forecast.days.slice();

  // Prefer the pipeline-provided elapsed days when present (snapshot in the
  // past); they already carry the correct balances and charges.
  if (forecast.priorDays.length > 0) {
    return [...forecast.priorDays, ...forward];
  }

  const windowStart = lastPastAnchor(todayIso);
  if (windowStart >= visibleStart) return forward; // nothing elapsed this period

  // Aggregate the net bank delta per elapsed day from the timeline's past
  // records (bank charges, debit charges, and credit-card bills all move the
  // bank balance on their shown date; their `.amount` matches the pipeline's
  // per-date bank delta).
  const items = buildForecastTimeline({
    forecast,
    threshold: 0,
    filter: 'all',
    ledger,
    templates,
    cards,
    todayIso,
  });
  const byDate = new Map<string, { delta: number; charges: ProjectionCharge[] }>();
  for (const item of items) {
    if (item.kind !== 'charge') continue;
    if (item.date < windowStart || item.date >= visibleStart) continue;
    const bucket = byDate.get(item.date) ?? { delta: 0, charges: [] };
    bucket.delta += item.amount;
    bucket.charges.push(chargeFromItem(item));
    byDate.set(item.date, bucket);
  }

  // Reconstruct backward: balance at the start of the window is today's
  // opening balance minus every elapsed delta.
  const todayBalance = forecast.days[0]?.balance ?? 0;
  let running = todayBalance;
  for (const bucket of byDate.values()) running -= bucket.delta;

  const elapsed: DailyProjection[] = [];
  for (let date = windowStart; date < visibleStart; date = addDays(date, 1)) {
    const bucket = byDate.get(date);
    const delta = bucket?.delta ?? 0;
    running += delta;
    elapsed.push({
      date,
      balance: running,
      delta,
      charges: bucket?.charges ?? [],
      isAnchor: Number(date.slice(8, 10)) === 10,
    });
  }

  return [...elapsed, ...forward];
};

/** Today as YYYY-MM-DD in the user's local time zone. */
const todayIsoLocal = (): string => {
  const date = new Date();
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
};

/**
 * Most recent past "anchor" (10th of a month — matches the forecast
 * pipeline's anchor convention). If today is before the 10th, returns
 * the 10th of the previous month.
 */
const lastPastAnchor = (todayIso: string): string => {
  const [yearPart, monthPart, dayPart] = todayIso.split('-');
  let year = Number(yearPart);
  let month = Number(monthPart);
  const day = Number(dayPart);
  if (day < 10) {
    month -= 1;
    if (month === 0) {
      month = 12;
      year -= 1;
    }
  }
  return `${year}-${String(month).padStart(2, '0')}-10`;
};
