import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { firstValueFrom } from 'rxjs';
import type {
  ForecastResult,
  LedgerEntry,
  Settings,
  ProjectionCharge,
  RecurringTemplate,
  CreditCard,
  PaymentProgress,
} from '@expenses/shared';
import {
  addMonths,
  descriptionLabel,
  firstBillingDayStrictlyAfter,
  generateVirtualOccurrences,
  paymentProgress,
} from '@expenses/shared';
import { ForecastApi } from './forecast.api';
import { BalanceChartComponent } from './balance-chart';

interface BilledChargeRow {
  date: string;
  description: string;
  amount: number;
  /** True when this sub-row is shown as already accounted for, not forecast action. */
  past?: boolean;
  /** True for entries that were marked cleared (status === 'cleared'). */
  cleared?: boolean;
  /** Optional X/Y badge — set when this row was generated by a fixed-term recurring template. */
  progress?: PaymentProgress | null;
  /** Set when this row was generated from a recurring template, so the
   * UI can offer a Skip button on future occurrences. */
  recurringId?: string;
}

interface ChargeItem {
  kind: 'charge';
  date: string;
  description: string;
  amount: number;
  channel: 'bank' | 'cc';
  cardId?: string;
  /** Set for bank-channel charges (single ledger entry). Absent for cc-bill rollups. */
  entryId?: string;
  /** True for rows shown as already accounted for, not forecast actions. */
  past?: boolean;
  /** True for entries that were marked cleared (status === 'cleared'). */
  cleared?: boolean;
  /** Individual charges aggregated into this cc-bill (chronological). */
  billedEntries?: BilledChargeRow[];
  /** Stable key for the expand/collapse toggle of a cc-bill. */
  billKey?: string;
  /** Optional X/Y badge — set when this charge came from a fixed-term recurring template. */
  progress?: PaymentProgress | null;
  /** Set when this charge was generated from a recurring template, so
   * the UI can offer a Skip button on future occurrences. */
  recurringId?: string;
}

interface AnchorItem {
  kind: 'anchor';
  date: string;
  balance: number;
  belowThreshold: boolean;
}

type TimelineItem = ChargeItem | AnchorItem;
type ChannelFilter = 'all' | 'bank' | 'cc' | 'anchors';

interface CardSummary {
  cardId: string;
  name: string;
  openingDebit: number;
  nextAnchorDate: string;
  nextAnchorOutstanding: number;
  billingDay: number;
}

@Component({
  selector: 'app-forecast-home',
  standalone: true,
  imports: [BalanceChartComponent, ReactiveFormsModule],
  templateUrl: './forecast-home.html',
  styleUrl: './forecast-home.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ForecastHomeComponent {
  private readonly api = inject(ForecastApi);
  private readonly fb = inject(FormBuilder);

  protected readonly forecast = signal<ForecastResult | null>(null);
  protected readonly settings = signal<Settings | null>(null);
  protected readonly ledger = signal<LedgerEntry[]>([]);
  protected readonly templates = signal<RecurringTemplate[]>([]);
  protected readonly cards = signal<CreditCard[]>([]);
  protected readonly error = signal<string | null>(null);
  protected readonly loading = signal(true);
  protected readonly channelFilter = signal<ChannelFilter>('all');
  /** Set of billKeys currently expanded to show their contributing charges. */
  protected readonly expandedBills = signal<ReadonlySet<string>>(new Set());

  protected toggleBill(key: string): void {
    const cur = this.expandedBills();
    const next = new Set(cur);
    if (next.has(key)) next.delete(key); else next.add(key);
    this.expandedBills.set(next);
  }

  protected isBillExpanded(key: string): boolean {
    return this.expandedBills().has(key);
  }

  /** Which snapshot is being edited: 'bank', a cardId, or null. */
  protected readonly editing = signal<string | null>(null);
  protected readonly saving = signal(false);

  protected readonly bankForm = this.fb.nonNullable.group({
    bankBalance: [0, [Validators.required]],
    asOf: ['', [Validators.required]],
  });

  protected readonly cardForm = this.fb.nonNullable.group({
    currentDebit: [0, [Validators.required, Validators.min(0)]],
    asOf: ['', [Validators.required]],
    mode: ['credit' as 'credit' | 'debit', [Validators.required]],
  });

  /** Snackbar for clear/undo. Holds the cleared entry so we can restore it. */
  protected readonly snackbar = signal<{
    message: string;
    entry: LedgerEntry;
  } | null>(null);
  private snackbarTimer: ReturnType<typeof setTimeout> | null = null;

  protected readonly statusCopy = computed(() => {
    const status = this.forecast()?.status;
    switch (status) {
      case 'breach':
        return { label: 'Action needed', subtitle: 'Balance drops below safety threshold.' };
      case 'warning':
        return { label: 'Approaching limit', subtitle: 'Minimum balance is close to the threshold.' };
      case 'safe':
        return { label: 'On track', subtitle: 'Balance stays above the safety threshold.' };
      default:
        return { label: '—', subtitle: '' };
    }
  });

  /** Projected bank balance at the next anchor day (10th of month). */
  protected readonly nextAnchor = computed<{ date: string; balance: number; belowThreshold: boolean } | null>(() => {
    const f = this.forecast();
    if (!f) return null;
    const anchor = f.days.find((d) => d.isAnchor);
    if (!anchor) return null;
    const threshold = this.settings()?.threshold ?? 0;
    return {
      date: anchor.date,
      balance: anchor.balance,
      belowThreshold: anchor.balance < threshold,
    };
  });

  /** Per-card summary shown beside the chart: opening debit + the amount
   * this card will bill next, on its own billing day. Debit cards are
   * excluded — every charge already hit the bank, so there's nothing to
   * snapshot or schedule. */
  protected readonly cardSummaries = computed<CardSummary[]>(() => {
    const f = this.forecast();
    if (!f) return [];
    const debitIds = new Set(
      this.cards().filter((c) => c.mode === 'debit').map((c) => c.id),
    );
    return f.cards
      .filter((card) => !debitIds.has(card.cardId))
      .map((card) => {
        // The pipeline records outstanding *after* the billing-day reset
        // (it zeros at the start of a billing day past asOf, then writes
        // the row). So the amount that's actually about to be billed is
        // the outstanding from the day immediately preceding the next
        // isBillingDay entry. Skip the asOf row itself (idx 0) because
        // on asOf the pipeline does not reset.
        const billIdx = card.days.findIndex((d, idx) => idx > 0 && d.isBillingDay);
        const nextBillDate = billIdx > 0 ? card.days[billIdx]!.date : card.asOf;
        const nextBillAmount =
          billIdx > 0 ? card.days[billIdx - 1]!.outstanding : card.openingDebit;
        return {
          cardId: card.cardId,
          name: card.name,
          openingDebit: card.openingDebit,
          nextAnchorDate: nextBillDate,
          nextAnchorOutstanding: nextBillAmount,
          billingDay: card.billingDayOfMonth,
        };
      });
  });

  /** Charges + anchors interleaved chronologically. */
  protected readonly timeline = computed<TimelineItem[]>(() => {
    const f = this.forecast();
    if (!f) return [];
    const threshold = this.settings()?.threshold ?? 0;
    const filter = this.channelFilter();
    const items: TimelineItem[] = [];

    const today = todayIsoLocal();
    const windowStart = lastPastAnchor(today);
    const visibleStart = f.days[0]?.date ?? today;

    const ledger = this.ledger();
    const overriddenOccurrences = new Set<string>();
    for (const e of ledger) {
      if (e.occurrenceKey) overriddenOccurrences.add(e.occurrenceKey);
    }

    const virtualBillCandidates =
      windowStart < visibleStart
        ? generateVirtualOccurrences(this.templates(), addMonths(windowStart, -1), visibleStart)
            .filter(
              (e) =>
                e.date < visibleStart &&
                (!e.occurrenceKey || !overriddenOccurrences.has(e.occurrenceKey)),
            )
        : [];
    const virtualPast = virtualBillCandidates.filter((e) => e.date >= windowStart);
    const persistedHistorical = ledger.filter(
      (e) =>
        e.date >= windowStart &&
        e.date <= f.endDate &&
        (e.date < visibleStart || e.status === 'cleared'),
    );

    // ---- Historical context: actual cleared rows and already-past rows ----
    if (filter !== 'anchors') {
      const historicalBillRows = this.pastCreditCardBillItems(
        virtualBillCandidates,
        ledger,
        windowStart,
        visibleStart,
        f.endDate,
      );

      for (const e of [...virtualPast, ...persistedHistorical]) {
        if (this.rollsIntoCreditCardBill(e)) continue;
        const row = this.toPastChargeItem(e);
        if (filter === 'all' || row.channel === filter) {
          items.push(row);
        }
      }
      for (const row of historicalBillRows) {
        if (filter === 'all' || row.channel === filter) {
          items.push(row);
        }
      }
    }

    // ---- Future forecast from the server ----
    for (const day of f.days) {
      if (filter !== 'anchors') {
        for (const c of day.charges) {
          const row = this.toChargeItem(
            day.date,
            c,
            c.source.kind === 'cc-bill'
              ? this.accountedCreditCardEntriesForBill(
                  c.source.cardId,
                  day.date,
                  [...virtualPast, ...persistedHistorical],
                  windowStart,
                )
              : [],
          );
          if (filter === 'all' || row.channel === filter) {
            items.push(row);
          }
        }
      }
      if (day.isAnchor) {
        items.push({
          kind: 'anchor',
          date: day.date,
          balance: day.balance,
          belowThreshold: day.balance < threshold,
        });
      }
    }
    return items.sort((a, b) => {
      if (a.date !== b.date) return a.date < b.date ? -1 : 1;
      if (a.kind === b.kind) return 0;
      return a.kind === 'anchor' ? 1 : -1;
    });
  });

  constructor() {
    void this.load();
  }

  protected async load(): Promise<void> {
    this.loading.set(true);
    this.error.set(null);
    try {
      const [result, settings, ledger, templates, cards] = await Promise.all([
        firstValueFrom(this.api.getForecast()),
        firstValueFrom(this.api.getSettings()),
        firstValueFrom(this.api.listLedger()),
        firstValueFrom(this.api.listRecurring()),
        firstValueFrom(this.api.listCards()),
      ]);
      this.forecast.set(result);
      this.settings.set(settings);
      this.ledger.set(ledger);
      this.templates.set(templates);
      this.cards.set(cards);
    } catch (err) {
      this.error.set(err instanceof Error ? err.message : String(err));
    } finally {
      this.loading.set(false);
    }
  }

  protected setFilter(f: ChannelFilter): void {
    this.channelFilter.set(f);
  }

  protected fmt(amount: number): string {
    return new Intl.NumberFormat('he-IL', {
      style: 'currency', currency: 'ILS', maximumFractionDigits: 0,
    }).format(amount);
  }

  protected fmtDate(iso: string): string {
    const d = new Date(`${iso}T00:00:00`);
    return d.toLocaleDateString('en-GB', { day: '2-digit', month: 'short' });
  }

  protected fmtAnchorDate(iso: string): string {
    const d = new Date(`${iso}T00:00:00`);
    return d.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: '2-digit' });
  }

  protected iconFor(channel: 'bank' | 'cc'): string {
    return channel === 'bank' ? 'account_balance' : 'credit_card';
  }

  /** Strip any `[source]` Excel-import prefix from a description. */
  protected displayDesc(desc: string): string {
    return descriptionLabel(desc);
  }

  protected isAnchor(i: TimelineItem): i is AnchorItem {
    return i.kind === 'anchor';
  }

  protected isCharge(i: TimelineItem): i is ChargeItem {
    return i.kind === 'charge';
  }

  protected trackTimeline = (_: number, i: TimelineItem): string =>
    i.kind === 'anchor'
      ? `a:${i.date}`
      : `c:${i.date}:${i.entryId ?? i.description}:${i.past ? 'p' : 'f'}`;

  // ---------- Snapshot editing ----------

  protected isEditingBank(): boolean { return this.editing() === 'bank'; }
  protected isEditingCard(cardId: string): boolean { return this.editing() === cardId; }
  protected isAnyEdit(): boolean { return this.editing() !== null; }

  protected startEditBank(): void {
    const f = this.forecast();
    if (!f) return;
    this.bankForm.reset({ bankBalance: f.account.bankBalance, asOf: this.todayIso() });
    this.editing.set('bank');
  }

  protected startEditCard(cardId: string): void {
    const f = this.forecast();
    const card = f?.cards.find((c) => c.cardId === cardId);
    if (!card) return;
    const full = this.cards().find((c) => c.id === cardId);
    this.cardForm.reset({
      currentDebit: card.snapshotDebit,
      asOf: this.todayIso(),
      mode: full?.mode === 'debit' ? 'debit' : 'credit',
    });
    this.editing.set(cardId);
  }

  /** Local-time `YYYY-MM-DD` for prefilling date inputs. */
  private todayIso(): string {
    return new Date().toLocaleDateString('en-CA');
  }

  protected cancelEdit(): void {
    this.editing.set(null);
    this.error.set(null);
  }

  protected async saveBank(): Promise<void> {
    if (this.bankForm.invalid) { this.bankForm.markAllAsTouched(); return; }
    this.saving.set(true);
    this.error.set(null);
    try {
      const v = this.bankForm.getRawValue();
      const res = await firstValueFrom(this.api.patchAccount({
        bankBalance: v.bankBalance, asOf: v.asOf,
      }));
      this.forecast.set(res.forecast);
      this.editing.set(null);
    } catch (err) {
      this.error.set(err instanceof Error ? err.message : String(err));
    } finally {
      this.saving.set(false);
    }
  }

  protected async saveCard(cardId: string): Promise<void> {
    if (this.cardForm.invalid) { this.cardForm.markAllAsTouched(); return; }
    const f = this.forecast();
    const card = f?.cards.find((c) => c.cardId === cardId);
    if (!card) return;
    this.saving.set(true);
    this.error.set(null);
    try {
      const v = this.cardForm.getRawValue();
      const res = await firstValueFrom(this.api.updateCard(cardId, {
        name: card.name,
        currentDebit: v.currentDebit,
        asOf: v.asOf,
        billingDayOfMonth: card.billingDayOfMonth,
        mode: v.mode,
      }));
      this.forecast.set(res.forecast);
      // Refresh the cards signal so the next edit sees the new mode.
      try {
        const cards = await firstValueFrom(this.api.listCards());
        this.cards.set(cards);
      } catch {
        // best-effort refresh; the forecast itself is authoritative
      }
      this.editing.set(null);
    } catch (err) {
      this.error.set(err instanceof Error ? err.message : String(err));
    } finally {
      this.saving.set(false);
    }
  }

  // ---------- Clear / undo ----------

  protected async clearCharge(entryId: string): Promise<void> {
    if (this.isAnyEdit()) return;
    this.error.set(null);
    try {
      const res = await firstValueFrom(this.api.clearLedger(entryId));
      this.forecast.set(res.forecast);
      this.showSnackbar(`Cleared “${res.entity.description}”`, res.entity);
    } catch (err) {
      this.error.set(err instanceof Error ? err.message : String(err));
    }
  }

  protected async undoClear(): Promise<void> {
    const snack = this.snackbar();
    if (!snack) return;
    this.dismissSnackbar();
    const e = snack.entry;
    try {
      const body = {
        description: e.description,
        amount: e.amount,
        channel: e.channel,
        date: e.date,
        status: 'pending' as const,
        ...(e.recurringId != null ? { recurringId: e.recurringId } : {}),
        ...(e.occurrenceKey != null ? { occurrenceKey: e.occurrenceKey } : {}),
      };
      const res = await firstValueFrom(this.api.updateLedger(e.id, body));
      this.forecast.set(res.forecast);
    } catch (err) {
      this.error.set(err instanceof Error ? err.message : String(err));
    }
  }

  protected dismissSnackbar(): void {
    if (this.snackbarTimer) {
      clearTimeout(this.snackbarTimer);
      this.snackbarTimer = null;
    }
    this.snackbar.set(null);
  }

  private showSnackbar(message: string, entry: LedgerEntry): void {
    if (this.snackbarTimer) clearTimeout(this.snackbarTimer);
    this.snackbar.set({ message, entry });
    this.snackbarTimer = setTimeout(() => this.snackbar.set(null), 6000);
  }

  // ---------- Skip / unskip recurring occurrences ----------

  /**
   * Skip eligibility for an itemized cc-bill sub-row. Same logic as
   * `canSkip` but the sub-row doesn't carry the channel/cardId info
   * directly — it must be supplied from the parent bill item.
   */
  protected canSkipSub(parentCardId: string | undefined, sub: BilledChargeRow): boolean {
    if (!sub.recurringId) return false;
    if (sub.past || sub.cleared) return false;
    const f = this.forecast();
    if (!f || !parentCardId) return false;
    const asOf = f.cards.find((c) => c.cardId === parentCardId)?.asOf;
    if (!asOf) return false;
    return sub.date > asOf;
  }

  /**
   * True when the user can skip this occurrence. We require:
   * - It's tied to a recurring template (recurringId set).
   * - The occurrence is in the future relative to the relevant asOf —
   *   account.asOf for bank charges, card.asOf for cc charges.
   *   (Past occurrences represent real or in-flight bank movements; the
   *   user should use "mark as cleared" instead.)
   */
  protected canSkip(item: ChargeItem): boolean {
    if (!item.recurringId) return false;
    if (item.past || item.cleared) return false;
    const f = this.forecast();
    if (!f) return false;
    const asOf =
      item.channel === 'cc' && item.cardId
        ? f.cards.find((c) => c.cardId === item.cardId)?.asOf
        : f.account.asOf;
    if (!asOf) return false;
    return item.date > asOf;
  }

  /** True when this is a persisted skipped occurrence — show "Unskip"
   * instead. The pipeline already filters skipped occurrences from the
   * forecast so this never shows up via `forecast.days`; we keep this
   * helper for sub-row rendering where we may want to surface skipped
   * occurrences explicitly in a future iteration. */
  protected isSkipped(item: BilledChargeRow | ChargeItem): boolean {
    if (!item.recurringId) return false;
    const t = this.templates().find((x) => x.id === item.recurringId);
    return t?.skips?.includes(item.date) ?? false;
  }

  protected async skipOccurrence(recurringId: string, date: string): Promise<void> {
    if (!confirm(`Skip the occurrence on ${date}?`)) return;
    this.error.set(null);
    try {
      const res = await firstValueFrom(this.api.addRecurringSkip(recurringId, date));
      this.forecast.set(res.forecast);
      this.templates.update((arr) =>
        arr.map((t) => (t.id === recurringId ? res.entity : t)),
      );
    } catch (err) {
      // 409 SKIP_CONFLICT_CLEARED bubbles up here.
      const msg = err instanceof Error ? err.message : String(err);
      this.error.set(
        msg.includes('SKIP_CONFLICT_CLEARED')
          ? 'A cleared override exists for this occurrence. Un-clear it before skipping.'
          : msg,
      );
    }
  }

  protected async unskipOccurrence(recurringId: string, date: string): Promise<void> {
    this.error.set(null);
    try {
      const res = await firstValueFrom(this.api.removeRecurringSkip(recurringId, date));
      this.forecast.set(res.forecast);
      this.templates.update((arr) =>
        arr.map((t) => (t.id === recurringId ? res.entity : t)),
      );
    } catch (err) {
      this.error.set(err instanceof Error ? err.message : String(err));
    }
  }

  /** Look up payment progress (X/Y) for a single ledger entry. Returns
   * `null` when the entry isn't from a recurring template, the template
   * has no end date, or anything's missing. */
  private progressForEntry(entry: { date: string; recurringId?: string }): PaymentProgress | null {
    if (!entry.recurringId) return null;
    const t = this.templates().find((x) => x.id === entry.recurringId);
    if (!t) return null;
    return paymentProgress(t, entry.date);
  }

  private toChargeItem(
    date: string,
    c: ProjectionCharge,
    accountedBilledEntries: ReadonlyArray<LedgerEntry> = [],
  ): ChargeItem {
    if (c.source.kind === 'cc-bill') {
      const seen = new Set<string>();
      const toBilledRow = (e: LedgerEntry, accounted: boolean): BilledChargeRow => ({
        date: e.date,
        description: e.description,
        amount: e.amount,
        progress: this.progressForEntry(e),
        ...(accounted ? { past: true } : {}),
        ...(e.status === 'cleared' ? { cleared: true } : {}),
        ...(e.recurringId ? { recurringId: e.recurringId } : {}),
      });
      const billed: BilledChargeRow[] = [];
      for (const e of accountedBilledEntries) {
        seen.add(e.id);
        billed.push(toBilledRow(e, true));
      }
      for (const e of c.source.billedEntries ?? []) {
        if (seen.has(e.id)) continue;
        seen.add(e.id);
        billed.push(toBilledRow(e, false));
      }
      billed.sort((a, b) => (a.date < b.date ? -1 : a.date > b.date ? 1 : 0));
      const entriesTotal = billed.reduce((s, e) => s + e.amount, 0);
      // Any residual between the bill amount and the sum of itemized charges
      // is the rolled-up opening balance from the snapshot. Surface it as a
      // synthetic top sub-row so the breakdown stays consistent.
      const opening = c.amount - entriesTotal;
      const sub: BilledChargeRow[] = [];
      if (Math.abs(opening) > 0.005) {
        sub.push({
          date,
          description: 'Opening balance (from Excel snapshot)',
          amount: opening,
          past: true,
        });
      }
      for (const b of billed) sub.push(b);
      if (sub.length === 0) {
        sub.push({
          date,
          description: 'No itemized charges in this cycle.',
          amount: c.amount,
        });
      }
      return {
        kind: 'charge',
        date,
        description: c.description,
        amount: c.amount,
        channel: 'cc',
        cardId: c.source.cardId,
        billedEntries: sub,
        billKey: `${date}:${c.source.cardId}`,
      };
    }
    // Bank-channel ledger row — prefer pipeline-supplied recurringId
    // (works for virtual occurrences too); fall back to ledger lookup
    // for legacy persisted entries.
    const { entryId, recurringId } = c.source;
    const recurringIdResolved =
      recurringId ?? this.ledger().find((e) => e.id === entryId)?.recurringId;
    return {
      kind: 'charge',
      date,
      description: c.description,
      amount: c.amount,
      channel: 'bank',
      entryId,
      progress: recurringIdResolved
        ? this.progressForEntry({ date, recurringId: recurringIdResolved })
        : null,
      ...(recurringIdResolved ? { recurringId: recurringIdResolved } : {}),
    };
  }

  private toPastChargeItem(e: LedgerEntry): ChargeItem {
    const isCc = e.channel.startsWith('cc:');
    const cardId = isCc ? e.channel.slice(3) : undefined;
    const item: ChargeItem = {
      kind: 'charge',
      date: e.date,
      description: e.description,
      amount: e.amount,
      channel: isCc ? 'cc' : 'bank',
      entryId: e.id,
      past: true,
      cleared: e.status === 'cleared',
      progress: e.recurringId ? this.progressForEntry(e) : null,
    };
    if (cardId) item.cardId = cardId;
    if (e.recurringId) item.recurringId = e.recurringId;
    return item;
  }

  private rollsIntoCreditCardBill(e: LedgerEntry): boolean {
    if (!e.channel.startsWith('cc:')) return false;
    const card = this.cards().find((c) => c.id === e.channel.slice(3));
    return card != null && card.mode !== 'debit';
  }

  private accountedCreditCardEntriesForBill(
    cardId: string,
    billDate: string,
    entries: ReadonlyArray<LedgerEntry>,
    start: string,
  ): LedgerEntry[] {
    const card = this.cards().find((c) => c.id === cardId);
    if (!card || card.mode === 'debit') return [];
    const openingBillDate = firstBillingDayStrictlyAfter(card.asOf, card.billingDayOfMonth);
    return entries.filter(
      (e) => {
        if (e.date < start || e.channel !== `cc:${cardId}`) return false;
        const entryBillDate = firstBillingDayStrictlyAfter(e.date, card.billingDayOfMonth);
        if (entryBillDate !== billDate) return false;
        if (e.date <= card.asOf) {
          return card.currentDebit !== 0 && billDate === openingBillDate;
        }
        return true;
      },
    );
  }

  private pastCreditCardBillItems(
    virtuals: ReadonlyArray<LedgerEntry>,
    persisted: ReadonlyArray<LedgerEntry>,
    start: string,
    visibleStart: string,
    end: string,
  ): ChargeItem[] {
    type BillBucket = {
      billDate: string;
      cardId: string;
      entries: LedgerEntry[];
      accountedEntries: LedgerEntry[];
      openingDebit: number;
    };

    const cardsById = new Map(this.cards().map((card) => [card.id, card]));
    const buckets = new Map<string, BillBucket>();
    const bucketFor = (cardId: string, billDate: string): BillBucket => {
      const key = `${billDate}:${cardId}`;
      let bucket = buckets.get(key);
      if (!bucket) {
        bucket = { billDate, cardId, entries: [], accountedEntries: [], openingDebit: 0 };
        buckets.set(key, bucket);
      }
      return bucket;
    };
    const inPastWindow = (date: string): boolean =>
      date >= start && date < visibleStart && date <= end;

    for (const card of this.cards()) {
      if (card.mode === 'debit' || card.currentDebit === 0) continue;
      const billDate = firstBillingDayStrictlyAfter(card.asOf, card.billingDayOfMonth);
      if (inPastWindow(billDate)) {
        bucketFor(card.id, billDate).openingDebit += card.currentDebit;
      }
    }

    for (const e of [...virtuals, ...persisted]) {
      if (!e.channel.startsWith('cc:')) continue;
      const cardId = e.channel.slice(3);
      const card = cardsById.get(cardId);
      if (!card || card.mode === 'debit') continue;
      const billDate = firstBillingDayStrictlyAfter(e.date, card.billingDayOfMonth);
      if (inPastWindow(billDate)) {
        const bucket = bucketFor(cardId, billDate);
        const openingBillDate = firstBillingDayStrictlyAfter(card.asOf, card.billingDayOfMonth);
        if (e.date <= card.asOf && card.currentDebit !== 0 && billDate === openingBillDate) {
          bucket.accountedEntries.push(e);
        } else {
          bucket.entries.push(e);
        }
      }
    }

    const rows: ChargeItem[] = [];
    for (const bucket of buckets.values()) {
      const card = cardsById.get(bucket.cardId);
      if (!card) continue;
      const entriesTotal = bucket.entries.reduce((sum, e) => sum + e.amount, 0);
      const amount = entriesTotal - bucket.openingDebit;
      const parts: string[] = [];
      if (bucket.openingDebit > 0) parts.push('opening balance');
      if (bucket.entries.length > 0) {
        parts.push(`${bucket.entries.length} charge${bucket.entries.length === 1 ? '' : 's'}`);
      }
      const summary = parts.length > 0 ? parts.join(' + ') : '0 charges';
      const row = this.toChargeItem(bucket.billDate, {
        description: `Credit card bill (${card.name}, ${summary})`,
        amount,
        source: { kind: 'cc-bill', cardId: bucket.cardId, billedEntries: bucket.entries.slice() },
      }, bucket.accountedEntries);
      row.past = true;
      rows.push(row);
    }
    return rows;
  }
}

/** Today as YYYY-MM-DD in the user's local time zone. */
function todayIsoLocal(): string {
  const d = new Date();
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
}

/**
 * Most recent past "anchor" (10th of a month — matches the forecast
 * pipeline's anchor convention). If today is before the 10th, returns
 * the 10th of the previous month.
 */
function lastPastAnchor(todayIso: string): string {
  const [yStr, mStr, dStr] = todayIso.split('-');
  let y = Number(yStr);
  let m = Number(mStr);
  const d = Number(dStr);
  if (d < 10) {
    m -= 1;
    if (m === 0) {
      m = 12;
      y -= 1;
    }
  }
  return `${y}-${String(m).padStart(2, '0')}-10`;
}
